CREATE TABLE IF NOT EXISTS target_schema.dim_framingham_study
(
  RANDID varchar(255) not null,
  SEX char(3),
  TOTCHOL INT,
  AGE INT,
  SYSBP INT  ,
  DIABP INT ,
  CURSMOKE INT,
  CIGPDAY INT,
  BMI FLOAT,
  DIABETES INT,
  BPMEDS INT,
  HEARTRTE FLOAT,
  GLUCOSE INT,
  educ INT,
  PREVCHD INT,
  PREVAP INT,
  PREVMI INT,
  PREVSTRK INT,
  PREVHYP INT,
  TIME INT,
  PERIOD INT,
  HDLC INT,
  LDLC INT,
  DEATH Int,
  ANGINA Int,
  HOSPMI Int,
  MI_FCHD Int,
  ANYCHD Int,
  STROKE Int,
  CVD INT,
  HYPERTEN INT,
  TIMEAP numeric,
  TIMEMI numeric,
  TIMEMIFC numeric,
  TIMECHD numeric,
  TIMESTRK numeric,
  TIMECVD numeric,
  TIMEDTH numeric,
  TIMEHYP numeric,
  last_update timestamp
);

INSERT INTO target_schema.dim_framingham_study
(
  SELECT
    RANDID,
    SEX,
    TOTCHOL,
    AGE,
    SYSBP,
    DIABP,
    CURSMOKE,
    CIGPDAY,
    BMI,
    DIABETES,
    BPMEDS,
    HEARTRTE,
    GLUCOSE,
    educ,
    PREVCHD,
    PREVAP,
    PREVMI,
    PREVSTRK,
    PREVHYP,
    TIME,
    PERIOD,
    HDLC,
    LDLC,
    DEATH,
    ANGINA,
    HOSPMI,
    MI_FCHD,
    ANYCHD,
    STROKE,
    CVD,
    HYPERTEN,
    TIMEAP,
    TIMEMI,
    TIMEMIFC,
    TIMECHD,
    TIMESTRK,
    TIMECVD,
    TIMEDTH,
    TIMEHYP,
    last_update
  FROM target_schema.stg_heart_db_framingham_study
)

